# Ref: https://dev.to/aws-builders/containerize-react-app-with-docker-for-production-572b
# stage1 - build react app first
FROM node:lts-alpine3.14 as build
ARG PORT

WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY ./package.json /app/
RUN npm install
COPY . /app
RUN npm run build

# stage 2 - build the final image and copy the react build files
FROM node:lts-alpine3.14
COPY --from=build /app/dist /app
COPY --from=build /app/package.json /app
ENV PORT=${PORT}
EXPOSE ${PORT}
WORKDIR /app
RUN npm i
ENTRYPOINT [ "npm" ]
CMD ["run", "start-prod"]
