# Ref: https://dev.to/aws-builders/containerize-react-app-with-docker-for-production-572b
# stage1 - build react app first
FROM node:14-alpine3.10 as build
ARG PORT

WORKDIR /app
COPY package*.json ./
COPY tsconfig*.json ./
RUN  npm install
COPY . ./
RUN npm run build

FROM node:14-alpine3.10 as ts-remover
WORKDIR /app
COPY --from=build /app/package*.json ./
COPY --from=build /app/build ./
RUN npm install --only=production

# # stage 2 - build the final image and copy the react build files
FROM gcr.io/distroless/nodejs:14
WORKDIR /usr/app
COPY --from=ts-remover /app ./
USER 1000
CMD ["main.js"]